### ISSUE TITLE
Modificación de reporte 

### ISSUE THREAD

**Issue by luismanuel82** [informaticaipsfa/bienestar#101]
Agregar:
* Firma del afiliado
* recibido por
* sello
* Totalizar monto del reporte, mostrar la sumatoria

Dividir reporte en dos partes imprimir original y copia

Nota: se repite el comprobante uno para el afiliado, otro para el expediente

![16700844437201450287519928590443](https://user-images.githubusercontent.com/29709077/205450840-17582513-6358-41d2-8615-a864b9cce9bc.jpg)

**Comment by gesaodin** [comment]
ampliacion de campos 
hash: 80f916fff4f2cbdaf5e64cb6027c93257183d360

**Comment by informaticaipsfa** [comment]
Revisado y resuelto
![aaa](https://user-images.githubusercontent.com/31702873/227044712-42e2b41d-3eb3-4926-81dd-d90180ac9618.png)
