### ISSUE TITLE
Agregar en los requisitos

### ISSUE THREAD

**Issue by luismanuel82** [informaticaipsfa/bienestar#102]
1.- Cuenta bancaria.
2.- Constancia de Seguros Horizonte.
![requisitos](https://user-images.githubusercontent.com/29709077/211680455-c8db357e-6ffb-4f01-b2ab-168648511148.jpg)

**Comment by luismanuel82** [comment]
![requisitos](https://user-images.githubusercontent.com/29709077/211680229-356920db-b8dd-4251-9518-f481a4fca066.jpg)

**Comment by gesaodin** [comment]
Agregando datos 
Hash: 4396c1c238184c75ab74594710223cb3d9dedd4d

![Captura desde 2023-03-22 17-03-35](https://user-images.githubusercontent.com/11463651/227037725-5021e8e3-1db9-4434-a9d4-305b5477c3c7.png)

**Comment by informaticaipsfa** [comment]
Revisado sin novedad.
