### ISSUE TITLE
Caja de Texto Cuenta Bancaria

### ISSUE THREAD

**Issue by luismanuel82** [informaticaipsfa/bienestar#104]
Activar caja de texto para modificar cuenta ya que el afiliado trae su cuenta.

![cajaTexto](https://user-images.githubusercontent.com/29709077/211669739-23abda46-a39d-4151-a490-c97f7d3eacbd.jpg)

**Comment by gesaodin** [comment]
En la sección Datos Bancarios, para incluir una nueva cuenta es requerido seleccionar en el combo de **Datos Bancarios** -> OTRA, activando así los campos para ingresar una nueva cuenta de los afiliados previamente registrados al titular, en caso de requerir un tercero de agregarse un autorizado por el modulo de afiliación
