### ISSUE TITLE
Eliminar el Rif y razón social

### ISSUE THREAD

**Issue by luismanuel82** [informaticaipsfa/bienestar#105]
Ficha de reembolso (eliminar el Rif y razón social ya que eso lo carga la sesión de apoyo).

![rifRazSoc](https://user-images.githubusercontent.com/29709077/211676850-d65cf27e-2480-49cf-b439-d49c7b4c35da.jpg)

**Comment by informaticaipsfa** [comment]
En cuenta sin novedad.
