### ISSUE TITLE
Alargar el límite en el campo de fecha

### ISSUE THREAD

**Issue by luismanuel82** [informaticaipsfa/bienestar#106]
Ficha  de reembolso (alargar el límite en el campo de fecha ya que hay apoyos que pasan la fecha de más de 3 meses como apoyo)
se debe poder seleccionar 3 mese por arriba de la fecha actual

![modFecha](https://user-images.githubusercontent.com/29709077/211678911-1413025c-203d-414f-9927-47ab3e1324c5.jpg)

**Comment by gesaodin** [comment]
Eliminar validacion de limite de fecha
Hash: 41cd172db53a0cc47f9014ba972e6483ee7de9b8

**Comment by informaticaipsfa** [comment]
Verificado sin novedad.
