### ISSUE TITLE
Colocar una nota en reporte

### ISSUE THREAD

**Issue by luismanuel82** [informaticaipsfa/bienestar#107]
En  el reporte final colocar una nota donde diga: la aceptación de la documentación no implica la aprobación de la totalidad del monto.

![reporte](https://user-images.githubusercontent.com/29709077/211682224-adeb95f0-9add-4bd1-bf81-2c1871d13a69.jpg)

**Comment by gesaodin** [comment]
ampliacion de campos 
hash: 80f916fff4f2cbdaf5e64cb6027c93257183d360

**Comment by informaticaipsfa** [comment]
Revisado y Resuelto
![aaa](https://user-images.githubusercontent.com/31702873/227044461-fdb3d379-96fb-40fa-9a61-7682d2fd73ba.png)
