### ISSUE TITLE
Numeración histórico de reembolso 

### ISSUE THREAD

**Issue by luismanuel82** [informaticaipsfa/bienestar#109]
En el histórico de reembolso la numeración incia en 0000000 lo 
correcto seria 0000001 
![numeracionRee](https://user-images.githubusercontent.com/29709077/213429177-7f6d2264-be41-4065-b4d9-ac7acbcec971.jpg)

**Comment by gesaodin** [comment]
El semillero estaba sin iniciar por eso arranco en cero
