### ISSUE TITLE
Notación Métrica

### ISSUE THREAD

**Issue by luismanuel82** [informaticaipsfa/bienestar#112]
Ajustar en todos los campos el decimal actualmente esta con punto (.), sustituir por el la coma (,)
Icluyendo el campo Monto:

![notacionMetrica](https://user-images.githubusercontent.com/29709077/212962096-3131b14e-430c-4bb7-8d97-1c84c2779e4b.jpg)

**Comment by gesaodin** [comment]
Verificar los reportes ya que el punto decimal se usa para realizar calculos a nivel computacional. se sugiere mantener dicho formato. 

En cuanto a los reportes si puede agregarse la coma, y en caso de que un reporte no lo tenga hacer la recomendación
