### ISSUE TITLE
Requisitos para solicitar Apoyo

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#117]
DOCUMENTACIÓN REQUERIDA PARA APOYOS ECONÓMICOS

La opción de Constancia de Agotamiento de Seguros Horizonte, C.A  (opcional). 

![Captura desde 2023-02-27 16-05-43](https://user-images.githubusercontent.com/31702873/221672292-0ebaef8a-b781-4afe-ab00-af21423f0d53.png)

**Comment by gesaodin** [comment]
Se ha realizado una actualización comentando el código a fine de volver a usar mas adelante
Adjunto código: 5c10d2352e58882f349423235c27000cc84edaab

**Comment by informaticaipsfa** [comment]
Despliegue de actualización verificada.

![Captura desde 2023-02-27 16-27-26](https://user-images.githubusercontent.com/31702873/221678172-78362df2-339c-4c4e-ad5b-b3fb84285dd9.png)
