### ISSUE TITLE
Datos de Reebolso

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#120]
Datos de reebolso agregar en los Conceptos:

- Agregar, Intervención Quirúrgica .
- requisito previo para el modal, Acta de Defunción (Original).

![Captura desde 2023-02-27 17-35-16](https://user-images.githubusercontent.com/31702873/221856355-972245bb-6894-4db6-b3a9-3c252a054802.png)

**Comment by gesaodin** [comment]
Proceso actualizado en dos capas con seguros funerarios

ID: f871de2cbeb5558041cbd6aa8be66c4b70323171

![Captura desde 2023-04-20 09-53-14](https://user-images.githubusercontent.com/11463651/233390712-ad651c13-c96a-4b95-9a3f-47f5f2efe160.png)

**Comment by informaticaipsfa** [comment]
verificado sin novedad
