### ISSUE TITLE
Datos de Reembolso

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#122]
**En los Datos del Reembolso se requiere agregar en el tipo de conceptos lo siguiente:**

1.-  Hospitalización.
2.-Intervención Quirúrgica.
3.-Gastos Funerarios
        3.1.-requiere el siguiente requisito: Acta de Defunción.

![Captura desde 2023-02-27 17-35-16](https://user-images.githubusercontent.com/31702873/221942752-a4054359-21a9-48f9-bdb5-fd02e742a3e1.png)

**Comment by gesaodin** [comment]
Agregando 
Hospitalizacion,
Funerarios
Intervencion

ID: 534a363db793449425608bba056a899175022524

![Captura desde 2023-04-20 10-33-51](https://user-images.githubusercontent.com/11463651/233399433-dc724965-dd59-478e-9109-397670c7375f.png)
![Captura desde 2023-04-20 09-53-14](https://user-images.githubusercontent.com/11463651/233399437-76afcb6a-37d2-45de-bb60-133536a523c5.png)
![Captura desde 2023-04-20 09-53-42](https://user-images.githubusercontent.com/11463651/233399438-329d2ea1-02cf-4383-96b8-8e789d804532.png)

![image](https://user-images.githubusercontent.com/11463651/233399396-fad58e89-c89d-4533-8636-cbcd6f446407.png)

**Comment by informaticaipsfa** [comment]
verificado sin novedad
