### ISSUE TITLE
Tipos de Conceptos en Datos de Reembolso (Cosulta)

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#125]
En datos de Reembolso, eliminar en tipo de concepto Consulta lo siguiente:

1. Carta de Rechazo de Seguros Horizonte
 

![Captura desde 2023-02-28 15-39-54](https://user-images.githubusercontent.com/31702873/221962034-63b2007b-6f99-45ef-b0f5-b0dc0f00fa46.png)

**Comment by gesaodin** [comment]
Dejando sin requisitos

ID: e231199565ac7248edba979927c955df19655f10

![Captura desde 2023-04-20 11-29-48](https://user-images.githubusercontent.com/11463651/233415120-c35970fc-86fe-4ed8-b402-bebcdb20f559.png)

**Comment by informaticaipsfa** [comment]
verificado sin novedad.
