### ISSUE TITLE
Tipos de Conceptos en Datos de Reembolso (Lentes)

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#127]
En los datos del Reembolso, tipo de concepto, incluir en los requisitos lo siguiente:

1.- Informe Medico firmado y sellado por el Medico Oftalmológo. 

**NOTA:** Tomar en cuenta que los lentes son un (1) par por paciente.

![Captura desde 2023-02-28 15-58-22](https://user-images.githubusercontent.com/31702873/221965532-8bd9e3b4-2c94-438d-8be0-1c9e17c634b0.png)

**Comment by gesaodin** [comment]
Agregando notas y opciones

ID: 0362bdbd49792c4075d0e6627f297fcf017b14c2
![Captura desde 2023-04-20 11-38-47](https://user-images.githubusercontent.com/11463651/233417409-45b43134-2268-42f0-9932-35a64814ad2f.png)

**Comment by informaticaipsfa** [comment]
verificado sin novedad.
