### ISSUE TITLE
#Buzon: Reembolsos

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#16]
Al pulsar el botón "Guardar Cambios" se visualiza un modal que indica "debe establecer un monto aprobado" este modal no aplica para el buzón de Sección de Recepción

**Comment by gesaodin** [comment]
2f3458a8206dfa2a319ac75ce1e1ac136a40d59f Se eliminaron las lineas que evitaban al modulo continuar
