### ISSUE TITLE
#Modal

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#2]
#Requisitos, agregar el texto
* Copia de la Cedula de Identidad y del Carnet vigente del militar 
y del familiar ampliada por ambas caras
* Copia de la Cédula de Identidad y del Carnet vigente del militar 
y del familiar ampliada por ambas caras (sí aplica)

**Comment by gesaodin** [comment]
f4112cd01ad0aa5d14873e1ca13bab57ed1521dd Correciónes
