### ISSUE TITLE
# Historico

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#31]
## Reporte
* Se debe visualizar la fecha de solicitud del caso
* Cambiar la palabra "Afiliado" por "Beneficiario" en la primera columna
* Cambiar la palabra "Beneficiario" por "Proveedor" en la tercera columna
* Se debe visualizar el total del monto solcitado

**Comment by gesaodin** [comment]
798566dd7b92bfc44ee5795de0ee7e6663a8859d Control de casos
