### ISSUE TITLE
Buzón: Datos 

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#33]
# Recepción
* En la ficha resumen no se visualiza la fecha de la solicitud
* alinear los títulos de las columnas de la tabla resumen del caso
* cambiar el símbolo "#" por el texto "Acción" 
* los datos numéricos en las celdas de la tabla deben estar alineados a la derecha
* el monto total solicitado debe estar en formato moneda
* unificar el texto "Observaciones" para los campos correspondientes
* en la tabla resumen de opiniones y estado,  no se visualiza el nombre de la columna "Estado", el texto del estado debe estar alineado a la derecha
* eliminar, en el  botón "agregar observación", el formato negrilla
* limpiar el campo de observación cuando se agrega una

**Comment by gesaodin** [comment]
0ee399a8be0f76dc3b3d6f836bb5a1d2665612ad Alineación y Cambios, en el botón de agregar observación no se modifico la negrita pero se uso mayúsculas y minúsculas
