### ISSUE TITLE
#Requisitos Principales

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#40]
## Requisitos principales
* agregar al final del texto"Copia de la Cédula de identidad y del Carnet del afiliado" , "por ambas caras" 
* cambiar el texto "Informe médico" por "Informe médico firmado y sellado por el médico tratante"

**Comment by gesaodin** [comment]
50bc48559ef6fc0362b75c83b64f6344c035465c Documento de Requisitos
