### ISSUE TITLE
Planilla

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#46]
* No se visualiza el estado, se visualiza el código del estado
* No se visualiza el número telefónico
* Cambiar el texto "solicitud de fe de vida" del recibo, por "Constancia de consignación de fe de vida"

**Comment by gesaodin** [comment]
6dc656399ee4e84d676bcda9598a26b2387279d3 en el caso del teléfono deben tener cargado los datos principales
