### ISSUE TITLE
#Datos, Convenio Seguros Horizonte

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#55]
* Agregar un modal de requisitos, cuando se seleccione en tipo de ayuda: Convenio Seguros Horizonte fondo de contingencia.
-Factura Original o Copia certificada por Seguros Horizonte
-Finiquito

**Comment by gesaodin** [comment]
Caso: d4f39c2
Datos->Modal; Tipo de Ayuda (Crear un nuevo requisito)
