### ISSUE TITLE
#Buzon, Recepción de Documentos

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#58]
* Agregar en el modal "Está seguro que desea procesar el apoyo XXX" al seleccionar el botón "Aceptar" el texto: "Imprimió la planilla de Solicitud?"

**Comment by gesaodin** [comment]
Caso: d14240d
se transcribió el texto: ¿Está seguro que desea procesar el apoyo ${num}. Imprimió la planilla de Solicitud?
