### ISSUE TITLE
#Histórico: Planilla

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#61]
## Emular la ficha del buzón ->Planilla al histórico de apoyo, salvo:
* No editables (todas)
* Cambiar la acción "eliminar" por "Cerrar Caso" fa-check-square o  fa-envelope en cada concepto
* Agregar un modal cuando se selecciona Cerrar Caso, que contenga las siguientes cajas
-numero de factura
-monto de la factura, 
-Fecha de la factura
-Fecha de entrega de la factura

**Comment by gesaodin** [comment]
Caso: 
51643d942e459bed65ccf40b071988bc0514d042
184f7ec5bd97f98d4647e7671411cc3c3b18ae1a
