### ISSUE TITLE
#Planilla, Carta Prótesis

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#67]
* Corregir en el texto de la carta:

Por medio de la presente, hacemos constar que el (la) ciudadano (a): "NOMBRE DEL BENEFICIARIO AFILIADO", titular de la cédula de identidad Nº "NUMERO DE CÉDULA DEL BENEFICIARIO" se encuentra afiliado(a) al Instituto de Previsión Social de la Fuerza Armada por ser PADRE del (la) "NOMBRE DEL MILITAR TITULAR", quien es miembro de la Fuerza Armada Nacional Bolivariana.

Por lo antes expuesto, este Instituto se compromete a pagar los gastos por concepto de " MOTIVO Y DESCRIPCIÓN", para el precitado afiliado, cuyo costo es de "MONTO EN LETRAS Y MONTO EN NÚMEROS" según se indica en el presupuesto Nº: "NÚMERO DEL PRESUPUESTO" de fecha "FECHA DEL PRESUPUESTO", monto del cual la empresa aseguradora cubrirá:  "MONTO EN LETRAS Y MONTO EN NÚMEROS" según constancia de fecha "FECHA DE LA CARTA AVAL DEL SEGURO" y la diferencia de "MONTO EN LETRAS Y MONTO EN NÚMEROS"  es el monto que este Instituto pagará en su totalidad.

Así mismo, se informa que cualquier información requerida para la tramitación del presente caso, puede ser solicitada a través nuestros teléfonos directos: (0212)-6931408 y (0212)-6092545, Departamento de Cuidado Integral de la Salud.

**Comment by gesaodin** [comment]
ad3fef2
