### ISSUE TITLE
#Planilla, Carta mastología

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#68]
* Corregir el texto:

Por medio de la presente, hacemos constar que el (la) ciudadano (a): "NOMBRE DEL BENEFICIARIO AFILIADO", titular de la cédula de identidad Nº "NÚMERO DE CÉDULA DEL BENEFICIARIO AFILIADO" se encuentra afiliado(a) al Instituto de Previsión Social de la Fuerza Armada por ser "PARENTESCO"  del (la) "NOMBRE DEL MILITAR TITULAR", quien es miembro de la Fuerza Armada Nacional Bolivariana.

Por lo antes expuesto, este Instituto se compromete a pagar por concepto de "MOTIVO DE LA CARTA AVAL Y ESTUDIO", la suma de "MONTO EN LETRAS Y MONTO EN NÚMEROS" que representa el "PORCENTAJE A CUBRIR POR EL IPSFA EN NÚMEROS" del costo del examen y el (la) precitado afiliado(a) pagará la suma de "MONTO EN LETRAS Y MONTO EN NÚMEROS" equivalente al "PORCENTAJE A CUBRIR POR EL AFILIADO EN NÚMEROS" restante, para cubrir el importe total del examen  "MONTO EN LETRAS Y MONTO EN NÚMEROS".

Así mismo, se informa que cualquier información requerida para la tramitación del presente caso, puede ser solicitada a nuestros teléfonos directos: (0212)-6931408 y (0212)-6092545, Departamento de Cuidado Integral de la Salud.

**Comment by gesaodin** [comment]
Caso: 372558b
