### ISSUE TITLE
#Datos, Dirección, Teléfonos

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#69]
* Debe ser obligatorio completar los campos de los números telefónicos, no se debe permitir avanzar cuando se coloca solo un carácter del número telefónico

**Comment by gesaodin** [comment]
Crear una función que certifique la existencia de número de teléfono.

```javascript 
ValidarNumeroTelefon(){
   if longitudTelefono != 11 {
      return false;
   }else{
      return true;
   }
}
```
