### ISSUE TITLE
#Planilla, 

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#75]
* Cambiar el texto:

Yo, "COLOCAR CAJA PARA ESCRIBIR EL NOMBRE DEL GERENTE",  titular de la cédula de identidad Nº "COLOCAR CAJA PARA ESCRIBIR EL NÚMERO DE CÉDULA DEL GERENTE", Militar en Servicio Activo con el cargo de "COLOCAR CAJA PARA ESCRIBIR EL CARGO Y NOMBRE DE LA GERENCIA O SUCURSAL" del IPSFA,  cuya sede principal se encuentra ubicada en LOS PRÓCERES, DISTRITO CAPITAL Teléfonos (0212) 6092307, 6092303, 6092304. De acuerdo a lo establecido en el Reglamento de la Ley de Seguridad Social de la Fuerza Armada, en su Artículo N° 24, el cual reza: "Los Comandos de Unidades y Jefaturas de dependencias de la Fuerza Armada Nacional, tienen la obligación, de coadyuvar a la tramitación de los documentos probatorios correspondientes y a las verificaciones a que hubiere lugar".
Certifico y doy fe que hoy "FECHA DE EMISIÓN" se presentó, la (el) ciudadana(o) "NOMBRE DEL AFILIADO", titular de la cédula de identidad N°: "NUMERO DE CÉDULA DEL AFILIADO", de "EDAD DEL AFILIADO" años de edad, Residenciado (a) en: "DIRECCIÓN Y NÚMEROS TELEFÓNICOS DEL AFILIADO" , con la finalidad de cumplir con el requisito exigido por el I.P.S.F.A.

**Comment by gesaodin** [comment]
5b07e950317326b1087e77490562a2ac1bb75fad :100:
