### ISSUE TITLE
Reportes

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#81]
Crear un panel que contenga los enlaces para:
1. Reembolsos
2. Apoyos Médicos
3. Carta Aval
4. Fe de Vida
5. Alto Costo
6. Tratamiento Prolongado
7. Préstamo de equipos

**Comment by gesaodin** [comment]
Confirmar tarea aunque la doy por finalizada
![image](https://user-images.githubusercontent.com/11463651/37458614-eb16a3b4-281b-11e8-8e01-d945575b506f.png)
