### ISSUE TITLE
#Planilla, Apoyo Ecónomo, monto a cubrir por el IPSFA

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#83]
El total del monto a cubrir por el IPSFA no es correcto, se visualiza el mismo monto total del presupuesto o monto solicitado, en la casilla monto total a cubrir por el IPSFA

![image](https://user-images.githubusercontent.com/31702873/32621228-7942f306-c555-11e7-95b9-6a398728b5a7.png)

**Comment by gesaodin** [comment]
0d70931375b1736af6b5577b0cdaeca9e9bad09f
