### ISSUE TITLE
Generar memo de remisión

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#84]
![image](https://user-images.githubusercontent.com/31702873/33187903-bc1bd67c-d06b-11e7-8749-ab3f0d64eec3.png)

**Comment by gesaodin** [comment]
Se deben tener casos que evaluar o que cumplan el ciclo del sistema verificar
![image](https://user-images.githubusercontent.com/11463651/37458725-4d80b94a-281c-11e8-8339-9a92170a62c2.png)
