### ISSUE TITLE
Reporte y oficio

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#85]
* Incluir el texto : "EL REPORTE SERÁ CONSTRUIDO CON LOS CASOS QUE SE VISUALIZAN EN PANTALLA, PARA EXCLUIR UN CASO DEL REPORTE HAGA “CLIC” CON EL RATÓN SOBRE EL CASO QUE DESEE EXCLUIR, LUEGO PRESIONE EL BOTÓN REPORTE Y OFICIO PARA GENERAR AMBOS DOCUMENTOS"

**Comment by gesaodin** [comment]
![image](https://user-images.githubusercontent.com/11463651/37458805-87ec0fee-281c-11e8-9d15-f102cd1c3a79.png)
