### ISSUE TITLE
Apoyo Medico

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/bienestar#90]
En la Interfaz de Apoyo Médico, se debe reemplazar la palabra Presupuesto por la palabra Factura cuando se seleccione un caso a través de Seguros Horizonte

**Comment by gesaodin** [comment]
function requisitosAyudas() {
    var modal = $("#cmbtipoayuda option:selected").attr("desplegar");
    if (modal != undefined) {
        inactivarCheck(modal);
        $("#btnGenerar").attr("disabled", true);
        $("#" + modal).modal("show");
        $("#lblnpresupuesto").text("N° de Factura:");
        $("#lblfpresupuesto").text("Fecha de Factura:");
    } else {
        $("#lblnpresupuesto").text("N° de Presupuesto:");
        $("#lblfpresupuesto").text("Fecha de Presupuesto:");
        $("#btnGenerar").attr("disabled", false);
    }
}
