### ISSUE TITLE
Eliminar menu de la interfaz

### ISSUE THREAD

**Issue by gesaodin** [informaticaipsfa/bienestar#99]
En la actualidad los menus de: Tratamiento Prolongado y Medicamento de alto costo se llevan por la aplicacion de farmacia: SIGADISPFA

``
<img width="939" alt="Captura de Pantalla 2022-12-03 a la(s) 11 48 38 a  m" src="https://user-images.githubusercontent.com/11463651/205449683-3c97c96d-3047-4b16-9c9c-60c89c42d395.png">

**Comment by gesaodin** [comment]
#sol ff944ed2f120d261cbafbeada4af98f4ac4939bb

Eliminado mediante tag

**Comment by informaticaipsfa** [comment]
revisado.
